/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorUsuario;
import ec.edu.ups.modelo.Usuario;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author braya
 */
public class VentanaRegistrar extends javax.swing.JInternalFrame {

    private ControladorUsuario ctrlUsuario;
    int contador = 0;

    /**
     * Creates new form VentanaRegistrar
     */
    public VentanaRegistrar(ControladorUsuario ctrlUsuario) {
        initComponents();
        this.ctrlUsuario = ctrlUsuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        txtGenero = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JTextField();
        txtDia = new javax.swing.JTextField();
        txtMes = new javax.swing.JTextField();
        txtAño = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnTestigos = new javax.swing.JButton();
        btnJuez = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setText("Ingrese Nombre");

        jLabel2.setText("Ingrese Apellido");

        jLabel3.setText("Ingrese Cedula");

        jLabel4.setText("Ingrese Direccion");

        jLabel5.setText("Ingrese Genero");

        jLabel6.setText("Ingrese Fecha de Nacimiento");

        btnRegistrar.setText("Registrar Parejas");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel8.setText("Ingrese Correo");

        jLabel9.setText("Ingrese Contraseña");

        txtDia.setText("01");
        txtDia.setToolTipText("01");
        txtDia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDiaMouseClicked(evt);
            }
        });

        txtMes.setText("01");
        txtMes.setToolTipText("");

        txtAño.setText("1999");
        txtAño.setToolTipText("");

        jLabel7.setText("Dia");

        jLabel10.setText("Mes");

        jLabel11.setText("Año");

        btnTestigos.setText("Registrar Testigos");
        btnTestigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestigosActionPerformed(evt);
            }
        });

        btnJuez.setText("Registrar Juez");
        btnJuez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJuezActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancelar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(txtAño, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btnRegistrar)
                        .addGap(18, 18, 18)
                        .addComponent(btnTestigos)
                        .addGap(18, 18, 18)
                        .addComponent(btnJuez)
                        .addContainerGap(93, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtGenero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnTestigos)
                    .addComponent(btnJuez))
                .addGap(30, 30, 30)
                .addComponent(btnCancelar)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDiaMouseClicked
        // TODO add your handling code here:
        txtDia.setText("");
        txtMes.setText("");
        txtAño.setText("");
    }//GEN-LAST:event_txtDiaMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnTestigosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestigosActionPerformed
        // TODO add your handling code here:
        int dia = Integer.valueOf(txtDia.getText());
        int mes = Integer.valueOf(txtMes.getText());
        int anio = Integer.valueOf(txtAño.getText());
        Date fecha = new Date(anio-1900, mes, dia);
        
        if (!txtNombre.getText().isEmpty() || !txtApellido.getText().isEmpty() || !txtCedula.getText().isEmpty()
                || !txtDireccion.getText().isEmpty() || !txtGenero.getText().isEmpty() || !txtDia.getText().isEmpty() 
                || !txtMes.getText().isEmpty() || !txtAño.getText().isEmpty() || !txtCorreo.getText().isEmpty() || !txtContraseña.getText().isEmpty()) {
            if (ctrlUsuario.comprobarCorreo(txtCorreo.getText())) {
                contador++;
                var us = new Usuario(txtNombre.getText(), txtApellido.getText(), txtCedula.getText(), txtDireccion.getText(), txtGenero.getText(), fecha, txtCorreo.getText(), txtContraseña.getText(), "Testigos") {};
                ctrlUsuario.create(us);
                System.out.println("new us = " + us);
                JOptionPane.showMessageDialog(this, "Registrado correctamente");
                if (contador == 2) {
                    btnTestigos.setEnabled(false);
                    contador=0;
                    vaciar();
                }else{
                    JOptionPane.showMessageDialog(this, "Ingrese siguiente testigo");
                    vaciar();
                }
            }else{
                JOptionPane.showMessageDialog(this, "Correo ya usado");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Hay campos en blanco");
        }
    }//GEN-LAST:event_btnTestigosActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        int dia = Integer.valueOf(txtDia.getText());
        int mes = Integer.valueOf(txtMes.getText());
        int anio = Integer.valueOf(txtAño.getText());
        Date fecha = new Date(anio-1900, mes, dia);
        
        if (!txtNombre.getText().isEmpty() || !txtApellido.getText().isEmpty() || !txtCedula.getText().isEmpty()
                || !txtDireccion.getText().isEmpty() || !txtGenero.getText().isEmpty() || !txtDia.getText().isEmpty() 
                || !txtMes.getText().isEmpty() || !txtAño.getText().isEmpty() || !txtCorreo.getText().isEmpty() || !txtContraseña.getText().isEmpty()) {
            if (ctrlUsuario.comprobarCorreo(txtCorreo.getText())) {
                contador++;
                var us = new Usuario(txtNombre.getText(), txtApellido.getText(), txtCedula.getText(), txtDireccion.getText(), txtGenero.getText(), fecha, txtCorreo.getText(), txtContraseña.getText(), "Pareja") {};
                ctrlUsuario.create(us);
                System.out.println("new us = " + us);
                JOptionPane.showMessageDialog(this, "Registrado correctamente");
                if (contador == 2) {
                    btnRegistrar.setEnabled(false);
                    vaciar();
                    contador = 0;
                }else{
                    vaciar();
                    JOptionPane.showMessageDialog(this, "Ingrese la siguiente persona");
                }
            }else{
                JOptionPane.showMessageDialog(this, "Correo ya usado");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Hay campos en blanco");
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnJuezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJuezActionPerformed
        // TODO add your handling code here:int dia = Integer.valueOf(txtDia.getText());
        int dia = Integer.valueOf(txtDia.getText());
        int mes = Integer.valueOf(txtMes.getText());
        int anio = Integer.valueOf(txtAño.getText());
        
        Date fecha = new Date(anio-1900, mes, dia);
        
        if (!txtNombre.getText().isEmpty() || !txtApellido.getText().isEmpty() || !txtCedula.getText().isEmpty()
                || !txtDireccion.getText().isEmpty() || !txtGenero.getText().isEmpty() || !txtDia.getText().isEmpty() 
                || !txtMes.getText().isEmpty() || !txtAño.getText().isEmpty() || !txtCorreo.getText().isEmpty() || !txtContraseña.getText().isEmpty()) {
            if (ctrlUsuario.comprobarCorreo(txtCorreo.getText())) {
                contador++;
                var us = new Usuario(txtNombre.getText(), txtApellido.getText(), txtCedula.getText(), txtDireccion.getText(), txtGenero.getText(), fecha, txtCorreo.getText(), txtContraseña.getText(), "Juez") {};
                ctrlUsuario.create(us);
                System.out.println("new us = " + us);
                JOptionPane.showMessageDialog(this, "Registrado correctamente");
                if (contador == 1) {
                    btnJuez.setEnabled(false);
                }
            }else{
                JOptionPane.showMessageDialog(this, "Correo ya usado");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Hay campos en blanco");
        }
        
    }//GEN-LAST:event_btnJuezActionPerformed

    public boolean comprobarCampos() {
        if (txtNombre.getText().isBlank() || txtApellido.getText().isBlank() || txtCedula.getText().isBlank() || txtDireccion.getText().isBlank() || txtDia.getText().isBlank() || txtMes.getText().isBlank() || txtAño.getText().isBlank() || txtCorreo.getText().isBlank() || txtContraseña.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Faltan Campos por llenar");
            return true;
        }
        return false;
    }

    public void vaciar() {
        txtApellido.setText("");
        txtCedula.setText("");
        txtDireccion.setText("");
        txtDia.setText("");
        txtMes.setText("");
        txtAño.setText("");
        txtGenero.setText("");
        txtNombre.setText("");
        txtCorreo.setText("");
        txtContraseña.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnJuez;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnTestigos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtMes;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
